### PR TITLE
Development

### PR DESCRIPTION
**Pull request by sgirardin**
Merge development branch

### CODE REVIEW

**Comment by SS-LAN** [comment]
Hi, as you used the NSGA-2 package by @onclave, I just wanted to know some information. Firstly i am using the same packagae for NSGA-2 to perfrom feature selection for DDoS dataset. 

So can you give me some information about your project on NSGA-2 Train rostering. I just wanted to understand how you made use of NSGA-2 and applied it to solve your problem

**Comment by sgirardin** [comment]
Hi @SS-LAN, 
I see you are new to github, it's better to raise an issue than to write in a Pull Request ;-) That's why Issues exists

Now your question is quite vague, I'll link (https://github.com/sgirardin/NSGA-II/blob/master/Giradin-Baumann-ACI-final-paper_Test.pdf) the paper that we wrote where we describe how we adapted the algorithm for our particular problem. 

Good Luck

**Comment by SS-LAN** [comment]
Thanks for replying.. Basically you answered my question by sharing the paper. And sorry about not writing in a pull request. Thanks anyway

**Comment by onclave** [comment]
Hello @sgirardin ,

It feels great to see that my simple implementation has helped you in in your research work. Since my repository is gaining some traction, I have recently added the ability to cite it directly using a DOI. It's in the README section.

If you have not already sent your paper for review / publication, would you be kind enough to provide the proper citation in your paper? Thanks!

Also, sorry for using the PR section to bring this up, I did not want to open a new issue regarding this and wanted to keep context w.r.t the discussion above.

> Debabrata Acharya. (2020, September 21). onclave/NSGA-II: an NSGA-II implementation using Java. Zenodo. http://doi.org/10.5281/zenodo.4042108

**Comment by sgirardin** [comment]
Hi @onclave 

Nice to hear that your repository is gaining traction. 
For the DOI Number, I'm sorry but we sent the paper 3 months ago, so we didn't have it then. But, we linked in the paper your GitHub repo URL. Hope it's still ok?

Have a nice day :-)

**Pull request merged**
